services:
  github-runner:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: runner.dockerfile
      args:
        - REPOSITORY_URL=${REPOSITORY_URL}
        - RUNNER_TOKEN=${RUNNER_TOKEN}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_HOST_GID=${DOCKER_HOST_GID}
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  cloudflared-http:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-http
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_HTTP_TUNNEL_TOKEN}

  cloudflared-ssh:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-ssh
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_SSH_TUNNEL_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80