services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/
      - ./sites/:/sites/
  
  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "--password=${DB_PASSWORD}"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

  wordpress:
    image: wordpress:php8.4-fpm
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ./sites/localhost/public:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "wp-config.php"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  database:
    name: database