{
 "title": "Docker-cAdvisor",
 "description": "cAdvisor with node selection",
 "tags": [
  "docker",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(container_cpu_user_seconds_total{job=\"$job\",from=\"docker\"}, name)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(container_cpu_user_seconds_total{name=~\"$name\"}, instance)"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "label_values(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\"}, interface)"
   },
   {
    "name": "sum_without",
    "label": "sum",
    "query": "unsum,instance,image,container_label_restartcount,device"
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)by (instance) / sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)) / sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m]))by (instance)"
    }
   ]
  },
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_cpu_user_seconds_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"} - container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"})",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "I/O Tx:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "I/O Rx:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Network Tx:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, name) ( irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) )",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Rx:sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, name) ( irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) )",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  }
 ]
}