services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./files/:/etc/nginx/
      - ${PROJECT_ROOT}/docker/web/apps/:/apps/
    networks:
      - main_proxy
      - public_proxy
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 150M
        reservations:
          cpus: 0.1
          memory: 50M

networks:
  main_proxy:
    name: main_proxy
    external: true
  public_proxy:
    name: public_proxy
    external: true