services:
  cloudflared-http:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-http
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_HTTP_TUNNEL_TOKEN}
    networks:
      - main_proxy

  cloudflared-ssh:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-ssh
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_SSH_TUNNEL_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - main_proxy

networks:
  main_proxy:
    name: main_proxy
    external: true