services:
  cloudflared-settings:
    &cloudflared-settings
      image: cloudflare/cloudflared:latest
      restart: unless-stopped
      networks:
        - main_proxy
      deploy:
        resources:
          limits:
            cpus: 0.5
            memory: 100M
          reservations:
            cpus: 0.1
            memory: 50M

  cloudflared-http:
    <<: *cloudflared-settings
    container_name: cloudflared-http
    command: tunnel --no-autoupdate run --token ${CL_HTTP_JHOFF_TOKEN}

  cloudflared-ssh:
    <<: *cloudflared-settings
    container_name: cloudflared-ssh
    command: tunnel --no-autoupdate run --token ${CL_SSH_SSHJHOFF_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  main_proxy:
    name: main_proxy
    external: true