services:
  github-runner:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPOSITORY_URL=${REPOSITORY_URL}
        - RUNNER_TOKEN=${RUNNER_TOKEN}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_HOST_GID=${DOCKER_HOST_GID}
        - CLOUDFLARE_SSH_TUNNEL_ID=${CL_SSH_SSHJHOFF_ID}
        - CLOUDFLARE_SSH_TUNNEL_TOKEN=${CL_SSH_SSHJHOFF_TOKEN}
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - main_proxy
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 0.5
          memory: 512M

networks:
  main_proxy:
    name: main_proxy
    external: true