x-runner-settings:
    &runner-settings
      user: "${UID}:${GID}"
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - UID=${UID}
          - GID=${GID}
          - DOCKER_HOST_GID=${DOCKER_HOST_GID}
          - CL_SSH_SSHJHOFF_ID=${CL_SSH_SSHJHOFF_ID}
          - CL_SSH_SSHJHOFF_TOKEN=${CL_SSH_SSHJHOFF_TOKEN}
          - RSYNC_RUNNER_PRIVATE_KEY=${RSYNC_RUNNER_PRIVATE_KEY}
          - GITHUB_RUNNER_PAT=${GITHUB_RUNNER_PAT}
      image: custom-github-runner:latest
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      privileged: true
      networks:
        - main_proxy
      deploy:
        resources:
          limits:
            cpus: 2
            memory: 4G

services:
  runner_home_server:
    <<: *runner-settings
    container_name: runner-home-server
    environment:
      REPOSITORY_NAME: home-server
      
  runner_half_horizons:
    <<: *runner-settings
    container_name: runner-half-horizons
    environment:
      REPOSITORY_NAME: half-horizons

networks:
  main_proxy:
    name: main_proxy
    external: true