name: Home server environment

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy in home server
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Replace tokens
        run: |
          sed -i "s|{{REPOSITORY_URL}}|${{ vars.REPOSITORY_URL }}|g" .env
          sed -i "s|{{GITHUB_RUNNER_TOKEN}}|${{ secrets.GITHUB_RUNNER_TOKEN }}|g" .env
          sed -i "s|{{CLOUDFLARE_HTTP_TUNEL_TOKEN}}|${{ secrets.CLOUDFLARE_HTTP_TUNNEL_TOKEN }}|g" .env
          sed -i "s|{{CLOUDFLARE_SSH_TUNEL_TOKEN}}|${{ secrets.CLOUDFLARE_SSH_TUNNEL_TOKEN }}|g" .env
      
      - name: Copying files
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: --no-perms -O --delete -Prltvz
          path: ./
          remote_path: ${{ vars.SERVER_PATH }}
          remote_host: ${{ secrets.SSH_DEPLOY_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}
        