name: Home server environment

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy in home server
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          name: ${{ secrets.SSH_DEPLOY_USER }}
          known_hosts: ${{ secrets.SSH_DEPLOY_KNOWN_HOSTS }}
          if_key_exists: fail
          config: |
            Host ${{ secrets.SSH_DEPLOY_HOST }}
              ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h --id ${{ secrets.CLOUDFLARE_SSH_TUNNEL_ID }} --secret ${{ secrets.CLOUDFLARE_SSH_TUNNEL_TOKEN }}
              IdentityFile ~/.ssh/${{ secrets.SSH_DEPLOY_USER }}
      
      - name: Add Cloudflare tunnel host key to known_hosts
        run: |
          cloudflared access ssh --hostname ${{ secrets.SSH_DEPLOY_HOST }} \
            --id ${{ secrets.CLOUDFLARE_SSH_TUNNEL_ID }} \
            --secret ${{ secrets.CLOUDFLARE_SSH_TUNNEL_TOKEN }} \
            --print-ssh-known-hosts >> ~/.ssh/known_hosts

      - name: Copying files
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: --no-perms -O --delete -Prltvz
          path: ./
          remote_path: ${{ vars.SERVER_PATH }}
          remote_host: ${{ secrets.SSH_DEPLOY_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}
        